# action.yml
name: 'Lint cnspec policies'
author: 'mondoohq'
description: 'Run cnspec bundle lint'
inputs:
  path:
    description: 'Specifies the path to root path of the bundles'
    required: true
    default: '.'
  output:
    description: 'Specifies the path for the sarif file'
    required: true
    default: 'results.sarif'
runs:
  using: 'docker'
  image: 'chrisrock/cnspec:latest'
  args:
   - bundle
   - lint
   - ${{ inputs.path }}
   - --output
   - sarif
   - --output-file
   - ${{ inputs.output }}